"""
Created on 21 Oct 2023

@author: Martin Vidjeskog
"""


from enum import Enum


class PieceType(Enum):
    """Different piece types."""

    HORIZONTAL_LEFT_BLOCKED_PIECE = 0
    HORIZONTAL_PIECE = 1
    HORIZONTAL_RIGHT_BLOCKED_PIECE = 2
    VERTICAL_PIECE = 3
    VERTICAL_TOP_BLOCKED_PIECE = 4
    VERTICAL_BOTTOM_BLOCKED_PIECE = 5
    TURN_NE_PIECE = 6
    TURN_SE_PIECE = 7
    TURN_SW_PIECE = 8
    TURN_NW_PIECE = 9
    INTERSECTION_LEFT_PIECE = 10
    INTERSECTION_UP_PIECE = 11
    INTERSECTION_RIGHT_PIECE = 12
    INTERSECTION_DOWN_PIECE = 13
    INTERSECTION_PIECE = 14
    BRIDGE_VERTICAL_PIECE = 16
    BRIDGE_HORIZONTAL_PIECE = 17
    TARGET_PIECE = 18
